apiVersion: v1
kind: Secret
metadata:
  name: dockerconfigjson
  namespace: cinemaabyss
data:
  .dockerconfigjson: ewogICJhdXRocyI6IHsKICAgICJnaGNyLmlvIjogewogICAgICAiYXV0aCI6ICJZVzUwYjI0eWVXRnJiM1pzWlhZNloyaHdYMmQ0YUZSVldIbGtTalF5UTFsc01qQkRNa0pNUkZKcFRWbzFXazlMT0ROTGN6TkdOQT09IgogICAgfQogIH0KfQo=
type: kubernetes.io/dockerconfigjson
